# Problem 1 

In [1]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
array = np.array([12, 7, 3, 18, 10])
print("Oluşturulan array:", array)


# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
sortedArray = np.sort(array)
print("Sıralanmış array:", sortedArray)



Oluşturulan array: [12  7  3 18 10]
Sıralanmış array: [ 3  7 10 12 18]


# Problem 2

In [5]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
dizi1 = np.array([10, 15, 30, 45, 60])
print(dizi1)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
dizi2 = np.arange(5, 16)
print(dizi2)

# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
dizi3 = np.arange(50, 101, 5)
print(dizi3)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
dizi4 = np.zeros(10)
print(dizi4)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
dizi5 = np.ones(10)
print(dizi5)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
dizi6 = np.linspace(0, 100, 5)
print(dizi6)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
dizi7 = np.random.randint(10, 31, 5)
print(dizi7)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
dizi8 = np.linspace(-1, 1, 10)
print(dizi8)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
matris = np.random.randint(10, 51, size=(3, 5))
print(f"Matris:\n {matris}")

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
satirToplam = np.sum(matris, axis=1)
sutunToplam = np.sum(matris, axis=0)
print(f"Satır toplamı: {satirToplam}")
print(f"Sütun toplamı: {sutunToplam}")

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
min = np.max(matris)
max = np.min(matris)
average = np.mean(matris)
print(f"En büyük değer: {max}")
print(f"En küçük değer: {min}")
print(f"Ortalama: {average}")

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
maxIndeks = np.unravel_index(np.argmax(matris), matris.shape)
print(f"En büyük değerin indeksi: {maxIndeks}")

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
dizi9 = np.arange(10, 21)
firstThree = dizi9[:3]
print(f"İlk 3 eleman: {firstThree}")

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
tersDizi = dizi9[::-1]
print(tersDizi)

# 15- Üretilen matrisin ilk satırını seçiniz.
ilkSatir = matris[0, :]
print(ilkSatir)

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
eleman = matris[1, 2]
print(f"2. satır 3. sütundaki eleman: {eleman}")

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
ilkSutunElemanlari = matris[:, 0]
print(f"Tüm satırların ilk elemanları: {ilkSutunElemanlari}")

# 18- Üretilen matrisin her bir elemanının karesini alınız.
matrisSquare = np.square(matris)
print(f"Matrisin her bir elemanının karesi:\n {matrisSquare}")

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
matrisRange = np.random.randint(-50, 51, size=(3, 5))
posEvenNum = matrisRange[(matrisRange > 0) & (matrisRange % 2 == 0)]
print(f"Matris:\n {matrisRange}" )
print(f"Pozitif çift sayılar: {posEvenNum}")


[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14 15]
[ 50  55  60  65  70  75  80  85  90  95 100]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[17 10 21 25 12]
[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]
Matris:
 [[46 36 42 43 36]
 [45 19 38 35 41]
 [48 11 31 44 28]]
Satır toplamı: [203 178 162]
Sütun toplamı: [139  66 111 122 105]
En büyük değer: 11
En küçük değer: 48
Ortalama: 36.2
En büyük değerin indeksi: (np.int64(2), np.int64(0))
İlk 3 eleman: [10 11 12]
[20 19 18 17 16 15 14 13 12 11 10]
[46 36 42 43 36]
2. satır 3. sütundaki eleman: 38
Tüm satırların ilk elemanları: [46 45 48]
Matrisin her bir elemanının karesi:
 [[2116 1296 1764 1849 1296]
 [2025  361 1444 1225 1681]
 [2304  121  961 1936  784]]
Matris:
 [[-19  13  28  47  29]
 [ 34   4 -33 -43 -38]
 [ 38  11 -46  16  11]]
Pozitif çift sayılar: [28 34  4 38 16]
